### ISSUE TITLE
Issues with getting it to work

### ISSUE THREAD

**Issue by theSage21** [theSage21/handwritten#1]
```
However, was getting the below error.

Traceback (most recent call last):
  File "get_hand.py", line 36, in <module>
    if not os.path.exists('images'):
NameError: name 'os' is not defined

so added : import os to the File "get_hand.py"


On running "python make_page.py 20 " the below error is thrown:

Creating pages folder
Traceback (most recent call last):
  File "make_page.py", line 36, in <module>
    for i in range(line_count):
TypeError: 'str' object cannot be interpreted as an integer

Pls. suggest any working solution.
```

**Comment by theSage21** [comment]
Resolved in codebase.
